PYTHON_TASKS = [
    {
        "id": 1, "set": 1,
        "title": "Ahoj, Pythone!",
        "story": "Vítej v Pythoním doupěti! Prvním kouzlem každého programátora je vypsat pozdrav.",
        "goal": "Použij print() a vypiš přesně: Ahoj, Pythone!",
        "starter_code": "# napiš svůj kód sem\n",
        "hint": 'print("Ahoj, Pythone!")',
        "check": 'assert "Ahoj, Pythone!" in _stdout_capture, "Nenašel jsem ve výstupu \'Ahoj, Pythone!\'"',
    },
    {
        "id": 2, "set": 1,
        "title": "Tvoje první proměnná",
        "story": "Proměnná je jako krabička, do které si uložíš hodnotu na později.",
        "goal": "Vytvoř proměnnou jmeno s tvým jménem (text) a pak ji vypiš pomocí print().",
        "starter_code": "jmeno = \"\"\n\n",
        "hint": 'jmeno = "Kadet"\nprint(jmeno)',
        "check": 'assert isinstance(jmeno, str) and len(jmeno) > 0, "Proměnná jmeno musí obsahovat nějaký text"\nassert jmeno in _stdout_capture, "Nezapomněl jsi vypsat jmeno pomocí print()?"',
    },
    {
        "id": 3, "set": 1,
        "title": "Počítání jako profík",
        "story": "Python umí počítat rychleji než kalkulačka.",
        "goal": "Ulož do proměnné vysledek součet čísel 15 a 27.",
        "starter_code": "vysledek = 0\n",
        "hint": "vysledek = 15 + 27",
        "check": 'assert vysledek == 42, f"Čekal jsem 42, mám {vysledek}"',
    },
    {
        "id": 4, "set": 1,
        "title": "Spojování textu",
        "story": "Texty (řetězce) jde spojovat dohromady pomocí f-stringů.",
        "goal": "Vytvoř proměnnou vek s číslem 12, pak proměnnou zprava, která pomocí f-stringu vypíše 'Je mi 12 let'.",
        "starter_code": "vek = 0\nzprava = \"\"\n",
        "hint": 'vek = 12\nzprava = f"Je mi {vek} let"',
        "check": 'assert vek == 12, "Proměnná vek musí být 12"\nassert zprava == "Je mi 12 let", f"Čekal jsem \'Je mi 12 let\', mám \'{zprava}\'"',
    },
    {
        "id": 5, "set": 1,
        "title": "Rozhodni se!",
        "story": "Programy umí reagovat jinak podle situace - k tomu slouží if.",
        "goal": "Vytvoř proměnnou cislo = 7. Pomocí if/else vypiš 'sude' pokud je sudé, jinak 'liche'.",
        "starter_code": "cislo = 7\n\n",
        "hint": 'cislo = 7\nif cislo % 2 == 0:\n    print("sude")\nelse:\n    print("liche")',
        "check": 'assert "liche" in _stdout_capture, "Číslo 7 je liché - měl by ses vypsat \'liche\'"',
    },
    {
        "id": 6, "set": 1,
        "title": "Opakuj se mnou (for)",
        "story": "Smyčka for umí zopakovat kus kódu vícekrát bez zbytečného opisování.",
        "goal": "Pomocí for a range(1, 6) vypiš čísla 1 až 5, každé na svůj řádek.",
        "starter_code": "\n",
        "hint": "for i in range(1, 6):\n    print(i)",
        "check": 'for _n in range(1, 6):\n    assert str(_n) in _stdout_capture, f"Chybí mi ve výstupu číslo {_n}"',
    },
    {
        "id": 7, "set": 2,
        "title": "Sečti smyčkou",
        "story": "Smyčky se dají použít i na sčítání - třeba součet čísel v seznamu.",
        "goal": "Máš seznam cisla. Pomocí for smyčky spočítej jejich součet do proměnné soucet.",
        "starter_code": "cisla = [3, 7, 2, 9, 5]\nsoucet = 0\n\n",
        "hint": "cisla = [3, 7, 2, 9, 5]\nsoucet = 0\nfor c in cisla:\n    soucet += c",
        "check": 'assert soucet == 26, f"Čekal jsem součet 26, mám {soucet}"',
    },
    {
        "id": 8, "set": 2,
        "title": "Seznam úkolů",
        "story": "Seznam (list) umí držet víc hodnot pohromadě, ve správném pořadí.",
        "goal": "Vytvoř seznam ukoly se třemi řetězci podle svého výběru, pak na konec přidej (append) 'ulozit soubor'.",
        "starter_code": "ukoly = []\n",
        "hint": 'ukoly = ["uklidit", "napsat kod", "najist se"]\nukoly.append("ulozit soubor")',
        "check": 'assert isinstance(ukoly, list) and len(ukoly) == 4, "Seznam ukoly musí mít nakonec 4 položky"\nassert ukoly[-1] == "ulozit soubor", "Poslední položka musí být \'ulozit soubor\'"',
    },
    {
        "id": 9, "set": 2,
        "title": "Projdi seznam",
        "story": "Přes seznam se dá procházet stejně jako přes range().",
        "goal": "Máš seznam zvirata. Pomocí for vypiš každé zvíře na svůj řádek.",
        "starter_code": "zvirata = [\"pes\", \"kocka\", \"papousek\"]\n\n",
        "hint": 'zvirata = ["pes", "kocka", "papousek"]\nfor z in zvirata:\n    print(z)',
        "check": 'for _z in ["pes", "kocka", "papousek"]:\n    assert _z in _stdout_capture, f"Chybí mi ve výstupu {_z}"',
    },
    {
        "id": 10, "set": 2,
        "title": "Slovník s informacemi",
        "story": "Slovník (dict) páruje klíč s hodnotou - třeba jméno s věkem.",
        "goal": "Vytvoř slovník kadet s klíči 'jmeno' (text) a 'level' (číslo 1).",
        "starter_code": "kadet = {}\n",
        "hint": 'kadet = {"jmeno": "Kadet", "level": 1}',
        "check": 'assert kadet.get("level") == 1, "Klíč \'level\' musí mít hodnotu 1"\nassert isinstance(kadet.get("jmeno"), str) and kadet.get("jmeno"), "Klíč \'jmeno\' musí obsahovat text"',
    },
    {
        "id": 11, "set": 3,
        "title": "Tvoje první funkce",
        "story": "Funkce je jako vlastní příkaz, který si sám naprogramuješ.",
        "goal": "Napiš funkci pozdrav(), která vypíše 'Ahoj z funkce!'. Pak ji zavolej.",
        "starter_code": "def pozdrav():\n    pass\n\n",
        "hint": 'def pozdrav():\n    print("Ahoj z funkce!")\n\npozdrav()',
        "check": 'assert "Ahoj z funkce!" in _stdout_capture, "Funkce pozdrav() musí vypsat \'Ahoj z funkce!\'"',
    },
    {
        "id": 12, "set": 3,
        "title": "Funkce s parametrem",
        "story": "Funkce může přijímat vstupní hodnoty (parametry) a s nimi pracovat.",
        "goal": "Napiš funkci secti(a, b), která vrátí (return) součet dvou čísel. Zavolej secti(4, 5) a výsledek ulož do proměnné vysledek.",
        "starter_code": "def secti(a, b):\n    pass\n\nvysledek = 0\n",
        "hint": "def secti(a, b):\n    return a + b\n\nvysledek = secti(4, 5)",
        "check": 'assert vysledek == 9, f"Čekal jsem 9, mám {vysledek}"',
    },
    {
        "id": 13, "set": 3,
        "title": "Podmínka uvnitř funkce",
        "story": "Funkce a podmínky se dají krásně kombinovat.",
        "goal": "Napiš funkci je_plnolety(vek), která vrátí True, pokud je vek >= 18, jinak False.",
        "starter_code": "def je_plnolety(vek):\n    pass\n",
        "hint": "def je_plnolety(vek):\n    return vek >= 18",
        "check": 'assert je_plnolety(20) == True, "je_plnolety(20) musí vrátit True"\nassert je_plnolety(10) == False, "je_plnolety(10) musí vrátit False"',
    },
    {
        "id": 14, "set": 3,
        "title": "While - opakuj, dokud...",
        "story": "Smyčka while opakuje kód, dokud platí podmínka.",
        "goal": "Pomocí while sniž proměnnou pocitadlo z 5 na 0 a při každém kroku ji vypiš.",
        "starter_code": "pocitadlo = 5\n\n",
        "hint": "pocitadlo = 5\nwhile pocitadlo > 0:\n    print(pocitadlo)\n    pocitadlo -= 1",
        "check": 'assert pocitadlo == 0, f"Na konci má být pocitadlo == 0, mám {pocitadlo}"\nfor _n in [5,4,3,2,1]:\n    assert str(_n) in _stdout_capture, f"Chybí mi ve výstupu {_n}"',
    },
    {
        "id": 15, "set": 3,
        "title": "Závěrečná mise: seznam jmen",
        "story": "Poslední úkol kombinuje funkce, seznamy i smyčky dohromady - přesně jako ve skutečném programování.",
        "goal": "Napiš funkci pozdrav_vsechny(jmena), která pro každé jméno v seznamu vypíše 'Ahoj, <jméno>!'. Zavolej ji se seznamem ['Ema', 'Jakub', 'Tereza'].",
        "starter_code": "def pozdrav_vsechny(jmena):\n    pass\n\n",
        "hint": 'def pozdrav_vsechny(jmena):\n    for j in jmena:\n        print(f"Ahoj, {j}!")\n\npozdrav_vsechny(["Ema", "Jakub", "Tereza"])',
        "check": 'for _j in ["Ema", "Jakub", "Tereza"]:\n    assert f"Ahoj, {_j}!" in _stdout_capture, f"Chybí pozdrav pro {_j}"',
    },

    {
        "id": 16, "set": 4,
        "title": "Velká a malá písmena",
        "story": "Level 2! Texty umí i samy sebe upravit - třeba přepnout na velká písmena.",
        "goal": "Vytvoř text = 'ahoj pythone' a proměnnou velka pomocí text.upper() (celý text velkými písmeny).",
        "starter_code": "text = \"ahoj pythone\"\nvelka = \"\"\n",
        "hint": 'text = "ahoj pythone"\nvelka = text.upper()',
        "check": 'assert velka == "AHOJ PYTHONE", f"Čekal jsem \'AHOJ PYTHONE\', mám \'{velka}\'"',
    },
    {
        "id": 17, "set": 4,
        "title": "Délka a znaky textu",
        "story": "Text je vlastně seznam znaků - dá se zjistit jeho délka i sáhnout na konkrétní písmeno.",
        "goal": "Máš slovo = 'kadet'. Ulož do delka jeho délku (len) a do prvni_pismeno jeho první znak (index 0).",
        "starter_code": "slovo = \"kadet\"\ndelka = 0\nprvni_pismeno = \"\"\n",
        "hint": 'slovo = "kadet"\ndelka = len(slovo)\nprvni_pismeno = slovo[0]',
        "check": 'assert delka == 5, f"Čekal jsem delka 5, mám {delka}"\nassert prvni_pismeno == "k", f"Čekal jsem \'k\', mám \'{prvni_pismeno}\'"',
    },
    {
        "id": 18, "set": 4,
        "title": "Rozděl větu na slova",
        "story": "split() rozseká text na kusy podle mezery (nebo jiného znaku).",
        "goal": "Máš veta = 'Python je super'. Pomocí .split() ulož do slova seznam jednotlivých slov.",
        "starter_code": "veta = \"Python je super\"\nslova = []\n",
        "hint": 'veta = "Python je super"\nslova = veta.split()',
        "check": 'assert slova == ["Python", "je", "super"], f"Čekal jsem [\'Python\', \'je\', \'super\'], mám {slova}"',
    },
    {
        "id": 19, "set": 4,
        "title": "Spoj seznam zpátky do textu",
        "story": "join() je opak split() - slepí seznam textů dohromady s oddělovačem, jaký si zvolíš.",
        "goal": "Máš slova = ['Ahoj', 'kadete']. Pomocí ' '.join(slova) ulož výsledek do vysledek (slova oddělená mezerou).",
        "starter_code": "slova = [\"Ahoj\", \"kadete\"]\nvysledek = \"\"\n",
        "hint": 'slova = ["Ahoj", "kadete"]\nvysledek = " ".join(slova)',
        "check": 'assert vysledek == "Ahoj kadete", f"Čekal jsem \'Ahoj kadete\', mám \'{vysledek}\'"',
    },
    {
        "id": 20, "set": 4,
        "title": "Řezy - vezmi jen kousek",
        "story": "Řez (slice) vybere jen část seznamu nebo textu - třeba 'od druhého do čtvrtého prvku'.",
        "goal": "Máš cisla = [10, 20, 30, 40, 50]. Ulož do vyrez prvky na indexech 1 až 3 (tedy cisla[1:4]).",
        "starter_code": "cisla = [10, 20, 30, 40, 50]\nvyrez = []\n",
        "hint": "cisla = [10, 20, 30, 40, 50]\nvyrez = cisla[1:4]",
        "check": 'assert vyrez == [20, 30, 40], f"Čekal jsem [20, 30, 40], mám {vyrez}"',
    },
    {
        "id": 21, "set": 4,
        "title": "Seřaď seznam",
        "story": "sorted() vrátí nový seřazený seznam, od nejmenšího po největší.",
        "goal": "Máš cisla = [5, 1, 4, 2, 3]. Ulož do serazeno výsledek sorted(cisla).",
        "starter_code": "cisla = [5, 1, 4, 2, 3]\nserazeno = []\n",
        "hint": "cisla = [5, 1, 4, 2, 3]\nserazeno = sorted(cisla)",
        "check": 'assert serazeno == [1, 2, 3, 4, 5], f"Čekal jsem [1,2,3,4,5], mám {serazeno}"',
    },
    {
        "id": 22, "set": 4,
        "title": "Největší, nejmenší, součet",
        "story": "Python má vestavěné funkce na časté úkoly, ať si je nemusíš psát sám.",
        "goal": "Máš cisla = [4, 9, 2, 7]. Ulož nejvetsi = max(cisla), nejmensi = min(cisla), soucet = sum(cisla).",
        "starter_code": "cisla = [4, 9, 2, 7]\nnejvetsi = 0\nnejmensi = 0\nsoucet = 0\n",
        "hint": "cisla = [4, 9, 2, 7]\nnejvetsi = max(cisla)\nnejmensi = min(cisla)\nsoucet = sum(cisla)",
        "check": 'assert nejvetsi == 9 and nejmensi == 2 and soucet == 22, f"mám nejvetsi={nejvetsi}, nejmensi={nejmensi}, soucet={soucet}"',
    },
    {
        "id": 23, "set": 4,
        "title": "Kombinuj podmínky (and / or)",
        "story": "Podmínky se dají spojovat - 'and' (obě musí platit), 'or' (aspoň jedna musí platit).",
        "goal": "Napiš funkci muze_hrat(vek, ma_povoleni), která vrátí True, jen pokud je vek >= 12 A ZÁROVEŇ ma_povoleni je True.",
        "starter_code": "def muze_hrat(vek, ma_povoleni):\n    pass\n",
        "hint": "def muze_hrat(vek, ma_povoleni):\n    return vek >= 12 and ma_povoleni",
        "check": 'assert muze_hrat(14, True) == True, "14 let + povolení -> True"\nassert muze_hrat(10, True) == False, "10 let -> False i s povolením"\nassert muze_hrat(14, False) == False, "bez povolení -> False"',
    },
    {
        "id": 24, "set": 4,
        "title": "Smyčka ve smyčce",
        "story": "Smyčky se dají vnořit jedna do druhé - třeba pro tabulku nebo mřížku.",
        "goal": "Pomocí dvou vnořených for smyček vypiš všechny dvojice (i, j) pro i i j v range(1, 3) ve formátu 'i-j' (celkem 4 řádky: 1-1, 1-2, 2-1, 2-2).",
        "starter_code": "\n",
        "hint": 'for i in range(1, 3):\n    for j in range(1, 3):\n        print(f"{i}-{j}")',
        "check": 'for _pair in ["1-1", "1-2", "2-1", "2-2"]:\n    assert _pair in _stdout_capture, f"Chybí mi dvojice {_pair}"',
    },
    {
        "id": 25, "set": 5,
        "title": "N-tice (tuple)",
        "story": "N-tice je jako seznam, ale jednou vytvořená se už nedá měnit - hodí se na pevné dvojice hodnot.",
        "goal": "Vytvoř n-tici bod = (3, 7). Pak si z ní pomocí rozbalení (x, y = bod) ulož souřadnice do x a y.",
        "starter_code": "bod = (0, 0)\nx = 0\ny = 0\n",
        "hint": "bod = (3, 7)\nx, y = bod",
        "check": 'assert x == 3 and y == 7, f"Čekal jsem x=3, y=7, mám x={x}, y={y}"',
    },
    {
        "id": 26, "set": 5,
        "title": "Množina bez duplicit",
        "story": "Množina (set) automaticky odstraní duplicitní hodnoty - hodí se na 'jaké unikátní hodnoty tu mám'.",
        "goal": "Máš cisla = [1, 2, 2, 3, 3, 3]. Pomocí set(cisla) ulož do unikatni množinu bez duplicit, pak pomocí len() ulož jejich počet do pocet.",
        "starter_code": "cisla = [1, 2, 2, 3, 3, 3]\nunikatni = set()\npocet = 0\n",
        "hint": "cisla = [1, 2, 2, 3, 3, 3]\nunikatni = set(cisla)\npocet = len(unikatni)",
        "check": 'assert unikatni == {1, 2, 3}, f"Čekal jsem {{1,2,3}}, mám {unikatni}"\nassert pocet == 3, f"Čekal jsem pocet 3, mám {pocet}"',
    },
    {
        "id": 27, "set": 5,
        "title": "Výchozí hodnota parametru",
        "story": "Parametr funkce může mít výchozí hodnotu, která se použije, když ho při volání nezadáš.",
        "goal": "Napiš funkci pozdrav(jmeno, pozdrav_slovo='Ahoj'), která vrátí f'{pozdrav_slovo}, {jmeno}!'.",
        "starter_code": "def pozdrav(jmeno, pozdrav_slovo=\"Ahoj\"):\n    pass\n",
        "hint": 'def pozdrav(jmeno, pozdrav_slovo="Ahoj"):\n    return f"{pozdrav_slovo}, {jmeno}!"',
        "check": 'assert pozdrav("Ema") == "Ahoj, Ema!", "Bez druhého argumentu má použít výchozí \'Ahoj\'"\nassert pozdrav("Ema", "Cau") == "Cau, Ema!", "Se zadaným druhým argumentem ho má použít místo výchozího"',
    },
    {
        "id": 28, "set": 5,
        "title": "Ošetři chybu (try/except)",
        "story": "Někdy se program pokusí o něco, co selže (třeba dělení nulou) - try/except to odchytí, ať program nespadne.",
        "goal": "Napiš try/except kolem vysledek = 10 / 0, který při chybě ZeroDivisionError vypíše 'Nelze delit nulou'.",
        "starter_code": "\n",
        "hint": 'try:\n    vysledek = 10 / 0\nexcept ZeroDivisionError:\n    print("Nelze delit nulou")',
        "check": 'assert "Nelze delit nulou" in _stdout_capture, "Měl jsi odchytit ZeroDivisionError a vypsat \'Nelze delit nulou\'"',
    },
    {
        "id": 29, "set": 5,
        "title": "Náhodné číslo",
        "story": "Modul random umí generovat náhodná čísla - třeba pro hru s kostkou.",
        "goal": "Naimportuj random, pak pomocí random.randint(1, 6) ulož do hod výsledek hodu kostkou (číslo 1 až 6).",
        "starter_code": "import random\nhod = 0\n",
        "hint": "import random\nhod = random.randint(1, 6)",
        "check": 'assert isinstance(hod, int) and 1 <= hod <= 6, f"hod musí být celé číslo 1 až 6, mám {hod}"',
    },
    {
        "id": 30, "set": 5,
        "title": "Závěrečná mise: hra s kostkou",
        "story": "Poslední mise levelu 2 - spoj náhodná čísla, podmínky i funkce do jedné malé hry.",
        "goal": "Napiš funkci hod_kostkou(), která vrátí náhodné číslo 1 až 6 (pomocí random.randint). Pak napiš funkci vyhodnot(hod), která vrátí 'vyhra' pokud je hod == 6, jinak 'zkus znovu'. Zavolej vyhodnot(6) a výsledek vypiš.",
        "starter_code": "import random\n\ndef hod_kostkou():\n    pass\n\ndef vyhodnot(hod):\n    pass\n\n",
        "hint": 'import random\n\ndef hod_kostkou():\n    return random.randint(1, 6)\n\ndef vyhodnot(hod):\n    if hod == 6:\n        return "vyhra"\n    else:\n        return "zkus znovu"\n\nprint(vyhodnot(6))',
        "check": 'assert vyhodnot(6) == "vyhra", "vyhodnot(6) musí vrátit \'vyhra\'"\nassert vyhodnot(3) == "zkus znovu", "vyhodnot(3) musí vrátit \'zkus znovu\'"\nassert "vyhra" in _stdout_capture, "Zapomněl jsi vypsat výsledek vyhodnot(6) pomocí print()"\n_test_hod = hod_kostkou()\nassert isinstance(_test_hod, int) and 1 <= _test_hod <= 6, "hod_kostkou() musí vracet číslo 1 až 6"',
    },
]


def all_tasks():
    return PYTHON_TASKS


def get_task(task_id: int):
    for t in PYTHON_TASKS:
        if t["id"] == task_id:
            return t
    return None
