PYTHON_TASKS = [
    {
        "id": 1, "set": 1,
        "title": "Ahoj, Pythone!",
        "tip": "Prvním kouzlem každého programátora je vypsat pozdrav.",
        "story": "Po zkratu jsem přišel o hlas. Pomoz mi promluvit: moje první slova ať jsou pozdrav.",
        "victory": "Slyším sám sebe! První slova po zkratu jsou venku.",
        "goal": "Použij print() a vypiš přesně: Ahoj, Pythone!",
        "starter_code": "# napiš svůj kód sem\n",
        "hint": 'print("Ahoj, Pythone!")',
        "check": 'assert "Ahoj, Pythone!" in _stdout_capture, "Nenašel jsem ve výstupu \'Ahoj, Pythone!\'"',
    },
    {
        "id": 2, "set": 1,
        "title": "Tvoje první proměnná",
        "tip": "Proměnná je jako krabička, do které si uložíš hodnotu na později.",
        "story": "Nevím, komu vlastně pomáhám. Zapiš mi do paměti své jméno, ať si ho pamatuju.",
        "victory": "Teď už vím, jak se jmenuješ. Je to uložené v paměti.",
        "goal": "Vytvoř proměnnou jmeno s tvým jménem (text) a pak ji vypiš pomocí print().",
        "starter_code": "jmeno = \"\"\n\n",
        "hint": 'jmeno = "Kadet"\nprint(jmeno)',
        "check": 'assert isinstance(jmeno, str) and len(jmeno) > 0, "Proměnná jmeno musí obsahovat nějaký text"\nassert jmeno in _stdout_capture, "Nezapomněl jsi vypsat jmeno pomocí print()?"',
    },
    {
        "id": 3, "set": 1,
        "title": "Počítání jako profík",
        "tip": "Python umí počítat rychleji než kalkulačka.",
        "story": "Počítadlo zásob ukazuje nesmysly. Začneme něčím jednoduchým: sčítáním.",
        "victory": "Čísla sedí a počítadlo zásob zase ukazuje pravdu.",
        "goal": "Ulož do proměnné vysledek součet čísel 15 a 27.",
        "starter_code": "vysledek = 0\n",
        "hint": "vysledek = 15 + 27",
        "check": 'assert vysledek == 42, f"Čekal jsem 42, mám {vysledek}"',
    },
    {
        "id": 4, "set": 1,
        "title": "Spojování textu",
        "tip": "Texty (řetězce) jde spojovat dohromady pomocí f-stringů.",
        "story": "Hlášení pro posádku má znít jako normální věta, ne jako hromada slov.",
        "victory": "Hlášení zní skoro jako od člověka.",
        "goal": "Vytvoř proměnnou vek s číslem 12, pak proměnnou zprava, která pomocí f-stringu vypíše 'Je mi 12 let'.",
        "starter_code": "vek = 0\nzprava = \"\"\n",
        "hint": 'vek = 12\nzprava = f"Je mi {vek} let"',
        "check": 'assert vek == 12, "Proměnná vek musí být 12"\nassert zprava == "Je mi 12 let", f"Čekal jsem \'Je mi 12 let\', mám \'{zprava}\'"',
    },
    {
        "id": 5, "set": 1,
        "title": "Rozhodni se!",
        "tip": "Programy umí reagovat jinak podle situace - k tomu slouží if.",
        "story": "Dveře do strojovny posílají sudé a liché kódy každý jinam. Já se potřebuju umět rozhodovat.",
        "victory": "Dveře vědí, kam s kterým kódem. Rozhodování mi funguje.",
        "goal": "Vytvoř proměnnou cislo = 7. Pomocí if/else vypiš 'sude' pokud je sudé, jinak 'liche'.",
        "starter_code": "cislo = 7\n\n",
        "hint": 'cislo = 7\nif cislo % 2 == 0:\n    print("sude")\nelse:\n    print("liche")',
        "check": 'assert "liche" in _stdout_capture, "Číslo 7 je liché - měl by ses vypsat \'liche\'"',
    },
    {
        "id": 6, "set": 1,
        "title": "Opakuj se mnou (for)",
        "tip": "Smyčka for umí zopakovat kus kódu vícekrát bez zbytečného opisování.",
        "story": "Kontrolky na panelu se rozsvěcují jedna po druhé. Psát každé číslo zvlášť je zbytečná dřina.",
        "victory": "Všech pět kontrolek svítí. Smyčka odvedla práci za mě.",
        "goal": "Pomocí for a range(1, 6) vypiš čísla 1 až 5, každé na svůj řádek.",
        "starter_code": "\n",
        "hint": "for i in range(1, 6):\n    print(i)",
        "check": 'for _n in range(1, 6):\n    assert str(_n) in _stdout_capture, f"Chybí mi ve výstupu číslo {_n}"',
    },
    {
        "id": 7, "set": 2,
        "title": "Sečti smyčkou",
        "tip": "Smyčky se dají použít i na sčítání - třeba součet čísel v seznamu.",
        "story": "Skladník zapsal počty beden za sebou. Sečti je, ať nemusím počítat každou zvlášť.",
        "victory": "Sklad je sečtený, takže vím, kolik toho máme.",
        "goal": "Máš seznam cisla. Pomocí for smyčky spočítej jejich součet do proměnné soucet.",
        "starter_code": "cisla = [3, 7, 2, 9, 5]\nsoucet = 0\n\n",
        "hint": "cisla = [3, 7, 2, 9, 5]\nsoucet = 0\nfor c in cisla:\n    soucet += c",
        "check": 'assert soucet == 26, f"Čekal jsem součet 26, mám {soucet}"',
    },
    {
        "id": 8, "set": 2,
        "title": "Seznam úkolů",
        "tip": "Seznam (list) umí držet víc hodnot pohromadě, ve správném pořadí.",
        "story": "Údržba stanice má spoustu práce a já si ji neumím zapamatovat. Potřebuju seznam úkolů.",
        "victory": "Seznam údržby mám u sebe a můžu ho dál doplňovat.",
        "goal": "Vytvoř seznam ukoly se třemi řetězci podle svého výběru, pak na konec přidej (append) 'ulozit soubor'.",
        "starter_code": "ukoly = []\n",
        "hint": 'ukoly = ["uklidit", "napsat kod", "najist se"]\nukoly.append("ulozit soubor")',
        "check": 'assert isinstance(ukoly, list) and len(ukoly) == 4, "Seznam ukoly musí mít nakonec 4 položky"\nassert ukoly[-1] == "ulozit soubor", "Poslední položka musí být \'ulozit soubor\'"',
    },
    {
        "id": 9, "set": 2,
        "title": "Projdi seznam",
        "tip": "Přes seznam se dá procházet stejně jako přes range().",
        "story": "V biologické sekci žijí zvířata. Obejdi je všechna a vypiš jejich jména.",
        "victory": "Všichni obyvatelé biologické sekce jsou na seznamu.",
        "goal": "Máš seznam zvirata. Pomocí for vypiš každé zvíře na svůj řádek.",
        "starter_code": "zvirata = [\"pes\", \"kocka\", \"papousek\"]\n\n",
        "hint": 'zvirata = ["pes", "kocka", "papousek"]\nfor z in zvirata:\n    print(z)',
        "check": 'for _z in ["pes", "kocka", "papousek"]:\n    assert _z in _stdout_capture, f"Chybí mi ve výstupu {_z}"',
    },
    {
        "id": 10, "set": 2,
        "title": "Slovník s informacemi",
        "tip": "Slovník (dict) páruje klíč s hodnotou - třeba jméno s věkem.",
        "story": "Každý člen posádky má průkaz s kolonkami. Vystavíme ho i tobě.",
        "victory": "Průkaz kadeta je vystavený. Teď jsi na palubě oficiálně.",
        "goal": "Vytvoř slovník kadet s klíči 'jmeno' (text) a 'level' (číslo 1).",
        "starter_code": "kadet = {}\n",
        "hint": 'kadet = {"jmeno": "Kadet", "level": 1}',
        "check": 'assert kadet.get("level") == 1, "Klíč \'level\' musí mít hodnotu 1"\nassert isinstance(kadet.get("jmeno"), str) and kadet.get("jmeno"), "Klíč \'jmeno\' musí obsahovat text"',
    },
    {
        "id": 11, "set": 3,
        "title": "Tvoje první funkce",
        "tip": "Funkce je jako vlastní příkaz, který si sám naprogramuješ.",
        "story": "Posádku zdravím pořád stejně. Uděláme z toho jediný příkaz, který stačí zavolat.",
        "victory": "Funkce funguje: stačí ji zavolat a pozdrav je tu.",
        "goal": "Napiš funkci pozdrav(), která vypíše 'Ahoj z funkce!'. Pak ji zavolej.",
        "starter_code": "def pozdrav():\n    pass\n\n",
        "hint": 'def pozdrav():\n    print("Ahoj z funkce!")\n\npozdrav()',
        "check": 'assert "Ahoj z funkce!" in _stdout_capture, "Funkce pozdrav() musí vypsat \'Ahoj z funkce!\'"',
    },
    {
        "id": 12, "set": 3,
        "title": "Funkce s parametrem",
        "tip": "Funkce může přijímat vstupní hodnoty (parametry) a s nimi pracovat.",
        "story": "Tentokrát nástroj na sčítání: dostane dvě čísla a vrátí výsledek.",
        "victory": "Nástroj na sčítání jde použít kdykoliv.",
        "goal": "Napiš funkci secti(a, b), která vrátí (return) součet dvou čísel. Zavolej secti(4, 5) a výsledek ulož do proměnné vysledek.",
        "starter_code": "def secti(a, b):\n    pass\n\nvysledek = 0\n",
        "hint": "def secti(a, b):\n    return a + b\n\nvysledek = secti(4, 5)",
        "check": 'assert vysledek == 9, f"Čekal jsem 9, mám {vysledek}"',
    },
    {
        "id": 13, "set": 3,
        "title": "Podmínka uvnitř funkce",
        "tip": "Funkce a podmínky se dají krásně kombinovat.",
        "story": "Do reaktorové sekce smí jen dospělí. Potřebuju funkci, která řekne ano, nebo ne.",
        "victory": "Hlídač u reaktoru umí rozhodovat podle věku.",
        "goal": "Napiš funkci je_plnolety(vek), která vrátí True, pokud je vek >= 18, jinak False.",
        "starter_code": "def je_plnolety(vek):\n    pass\n",
        "hint": "def je_plnolety(vek):\n    return vek >= 18",
        "check": 'assert je_plnolety(20) == True, "je_plnolety(20) musí vrátit True"\nassert je_plnolety(10) == False, "je_plnolety(10) musí vrátit False"',
    },
    {
        "id": 14, "set": 3,
        "title": "While - opakuj, dokud...",
        "tip": "Smyčka while opakuje kód, dokud platí podmínka.",
        "story": "Záchranné kapsle startují po odpočtu. Dokud není nula, počítám dál.",
        "victory": "Odpočet doběhl na nulu a smyčka se nezasekla.",
        "goal": "Pomocí while sniž proměnnou pocitadlo z 5 na 0 a při každém kroku ji vypiš.",
        "starter_code": "pocitadlo = 5\n\n",
        "hint": "pocitadlo = 5\nwhile pocitadlo > 0:\n    print(pocitadlo)\n    pocitadlo -= 1",
        "check": 'assert pocitadlo == 0, f"Na konci má být pocitadlo == 0, mám {pocitadlo}"\nfor _n in [5,4,3,2,1]:\n    assert str(_n) in _stdout_capture, f"Chybí mi ve výstupu {_n}"',
    },
    {
        "id": 15, "set": 3,
        "title": "Závěrečná mise: seznam jmen",
        "tip": "Poslední úkol kombinuje funkce, seznamy i smyčky dohromady - přesně jako ve skutečném programování.",
        "story": "Poslední nástroj dílny: pozdravit celou posádku najednou, ať se jména mění, jak chtějí.",
        "victory": "Celá posádka je pozdravená. Dílna je hotová.",
        "goal": "Napiš funkci pozdrav_vsechny(jmena), která pro každé jméno v seznamu vypíše 'Ahoj, <jméno>!'. Zavolej ji se seznamem ['Ema', 'Jakub', 'Tereza'].",
        "starter_code": "def pozdrav_vsechny(jmena):\n    pass\n\n",
        "hint": 'def pozdrav_vsechny(jmena):\n    for j in jmena:\n        print(f"Ahoj, {j}!")\n\npozdrav_vsechny(["Ema", "Jakub", "Tereza"])',
        "check": 'for _j in ["Ema", "Jakub", "Tereza"]:\n    assert f"Ahoj, {_j}!" in _stdout_capture, f"Chybí pozdrav pro {_j}"',
    },

    {
        "id": 16, "set": 4,
        "title": "Velká a malá písmena",
        "tip": "Texty umí samy sebe upravit, třeba přepnout na velká písmena.",
        "story": "Zprávy ze Země chodí malými písmeny, ale hlášení musí být velkými.",
        "victory": "Hlášení je velkými písmeny, slyší ho celá stanice.",
        "goal": "Vytvoř text = 'ahoj pythone' a proměnnou velka pomocí text.upper() (celý text velkými písmeny).",
        "starter_code": "text = \"ahoj pythone\"\nvelka = \"\"\n",
        "hint": 'text = "ahoj pythone"\nvelka = text.upper()',
        "check": 'assert velka == "AHOJ PYTHONE", f"Čekal jsem \'AHOJ PYTHONE\', mám \'{velka}\'"',
    },
    {
        "id": 17, "set": 4,
        "title": "Délka a znaky textu",
        "tip": "Text je vlastně seznam znaků - dá se zjistit jeho délka i sáhnout na konkrétní písmeno.",
        "story": "Volací znak lodi je kód, ve kterém záleží na délce i na prvním znaku.",
        "victory": "Délka i první znak hlásí správně.",
        "goal": "Máš slovo = 'kadet'. Ulož do delka jeho délku (len) a do prvni_pismeno jeho první znak (index 0).",
        "starter_code": "slovo = \"kadet\"\ndelka = 0\nprvni_pismeno = \"\"\n",
        "hint": 'slovo = "kadet"\ndelka = len(slovo)\nprvni_pismeno = slovo[0]',
        "check": 'assert delka == 5, f"Čekal jsem delka 5, mám {delka}"\nassert prvni_pismeno == "k", f"Čekal jsem \'k\', mám \'{prvni_pismeno}\'"',
    },
    {
        "id": 18, "set": 4,
        "title": "Rozděl větu na slova",
        "tip": "split() rozseká text na kusy podle mezery (nebo jiného znaku).",
        "story": "Vysílačka přijala celou větu v jednom kuse. Rozlož ji na jednotlivá slova.",
        "victory": "Věta je rozložená na slova.",
        "goal": "Máš veta = 'Python je super'. Pomocí .split() ulož do slova seznam jednotlivých slov.",
        "starter_code": "veta = \"Python je super\"\nslova = []\n",
        "hint": 'veta = "Python je super"\nslova = veta.split()',
        "check": 'assert slova == ["Python", "je", "super"], f"Čekal jsem [\'Python\', \'je\', \'super\'], mám {slova}"',
    },
    {
        "id": 19, "set": 4,
        "title": "Spoj seznam zpátky do textu",
        "tip": "join() je opak split() - slepí seznam textů dohromady s oddělovačem, jaký si zvolíš.",
        "story": "Teď naopak: ze slov složíme jedno hlášení.",
        "victory": "Slova jsou slepená do jednoho hlášení.",
        "goal": "Máš slova = ['Ahoj', 'kadete']. Pomocí ' '.join(slova) ulož výsledek do vysledek (slova oddělená mezerou).",
        "starter_code": "slova = [\"Ahoj\", \"kadete\"]\nvysledek = \"\"\n",
        "hint": 'slova = ["Ahoj", "kadete"]\nvysledek = " ".join(slova)',
        "check": 'assert vysledek == "Ahoj kadete", f"Čekal jsem \'Ahoj kadete\', mám \'{vysledek}\'"',
    },
    {
        "id": 20, "set": 4,
        "title": "Řezy - vezmi jen kousek",
        "tip": "Řez (slice) vybere jen část seznamu nebo textu - třeba 'od druhého do čtvrtého prvku'.",
        "story": "Záznam z kamer je dlouhý a já potřebuju jen jeho střední úsek.",
        "victory": "Vyřízl jsi přesně ten kousek, který jsem potřeboval.",
        "goal": "Máš cisla = [10, 20, 30, 40, 50]. Ulož do vyrez prvky na indexech 1 až 3 (tedy cisla[1:4]).",
        "starter_code": "cisla = [10, 20, 30, 40, 50]\nvyrez = []\n",
        "hint": "cisla = [10, 20, 30, 40, 50]\nvyrez = cisla[1:4]",
        "check": 'assert vyrez == [20, 30, 40], f"Čekal jsem [20, 30, 40], mám {vyrez}"',
    },
    {
        "id": 21, "set": 4,
        "title": "Seřaď seznam",
        "tip": "sorted() vrátí nový seřazený seznam, od nejmenšího po největší.",
        "story": "Měření ze senzorů přišla zamíchaná. Seřaď je od nejmenšího po největší.",
        "victory": "Měření stojí v pořádné řadě.",
        "goal": "Máš cisla = [5, 1, 4, 2, 3]. Ulož do serazeno výsledek sorted(cisla).",
        "starter_code": "cisla = [5, 1, 4, 2, 3]\nserazeno = []\n",
        "hint": "cisla = [5, 1, 4, 2, 3]\nserazeno = sorted(cisla)",
        "check": 'assert serazeno == [1, 2, 3, 4, 5], f"Čekal jsem [1,2,3,4,5], mám {serazeno}"',
    },
    {
        "id": 22, "set": 4,
        "title": "Největší, nejmenší, součet",
        "tip": "Python má vestavěné funkce na časté úkoly, ať si je nemusíš psát sám.",
        "story": "Z měření chci tři údaje: největší, nejmenší a součet.",
        "victory": "Všechny tři údaje sedí. Senzory mluví jasně.",
        "goal": "Máš cisla = [4, 9, 2, 7]. Ulož nejvetsi = max(cisla), nejmensi = min(cisla), soucet = sum(cisla).",
        "starter_code": "cisla = [4, 9, 2, 7]\nnejvetsi = 0\nnejmensi = 0\nsoucet = 0\n",
        "hint": "cisla = [4, 9, 2, 7]\nnejvetsi = max(cisla)\nnejmensi = min(cisla)\nsoucet = sum(cisla)",
        "check": 'assert nejvetsi == 9 and nejmensi == 2 and soucet == 22, f"mám nejvetsi={nejvetsi}, nejmensi={nejmensi}, soucet={soucet}"',
    },
    {
        "id": 23, "set": 4,
        "title": "Kombinuj podmínky (and / or)",
        "tip": "Podmínky se dají spojovat - 'and' (obě musí platit), 'or' (aspoň jedna musí platit).",
        "story": "Do simulátoru letu smí jen ten, komu to věk dovolí a kdo má povolení. Musí platit obojí zároveň.",
        "victory": "Simulátor pouští jen ty správné lidi.",
        "goal": "Napiš funkci muze_hrat(vek, ma_povoleni), která vrátí True, jen pokud je vek >= 12 A ZÁROVEŇ ma_povoleni je True.",
        "starter_code": "def muze_hrat(vek, ma_povoleni):\n    pass\n",
        "hint": "def muze_hrat(vek, ma_povoleni):\n    return vek >= 12 and ma_povoleni",
        "check": 'assert muze_hrat(14, True) == True, "14 let + povolení -> True"\nassert muze_hrat(10, True) == False, "10 let -> False i s povolením"\nassert muze_hrat(14, False) == False, "bez povolení -> False"',
    },
    {
        "id": 24, "set": 4,
        "title": "Smyčka ve smyčce",
        "tip": "Smyčky se dají vnořit jedna do druhé - třeba pro tabulku nebo mřížku.",
        "story": "Trup stanice kontroluju po sektorech: řádek po řádku a v každém sektor po sektoru. Smyčka ve smyčce.",
        "victory": "Všechny čtyři sektory jsou prohledané.",
        "goal": "Pomocí dvou vnořených for smyček vypiš všechny dvojice (i, j) pro i i j v range(1, 3) ve formátu 'i-j' (celkem 4 řádky: 1-1, 1-2, 2-1, 2-2).",
        "starter_code": "\n",
        "hint": 'for i in range(1, 3):\n    for j in range(1, 3):\n        print(f"{i}-{j}")',
        "check": 'for _pair in ["1-1", "1-2", "2-1", "2-2"]:\n    assert _pair in _stdout_capture, f"Chybí mi dvojice {_pair}"',
    },
    {
        "id": 25, "set": 5,
        "title": "N-tice (tuple)",
        "tip": "N-tice je jako seznam, ale jednou vytvořená se už nedá měnit - hodí se na pevné dvojice hodnot.",
        "story": "Souřadnice jsou dvojice čísel, která se nemá měnit: bod na mapě.",
        "victory": "Bod na mapě je zapsaný a rozdělený na x a y.",
        "goal": "Vytvoř n-tici bod = (3, 7). Pak si z ní pomocí rozbalení (x, y = bod) ulož souřadnice do x a y.",
        "starter_code": "bod = (0, 0)\nx = 0\ny = 0\n",
        "hint": "bod = (3, 7)\nx, y = bod",
        "check": 'assert x == 3 and y == 7, f"Čekal jsem x=3, y=7, mám x={x}, y={y}"',
    },
    {
        "id": 26, "set": 5,
        "title": "Množina bez duplicit",
        "tip": "Množina (set) automaticky odstraní duplicitní hodnoty - hodí se na 'jaké unikátní hodnoty tu mám'.",
        "story": "Anténa zachytila stejné signály několikrát. Každý chci mít jen jednou.",
        "victory": "Duplikáty zmizely a zůstaly jen různé signály.",
        "goal": "Máš cisla = [1, 2, 2, 3, 3, 3]. Pomocí set(cisla) ulož do unikatni množinu bez duplicit, pak pomocí len() ulož jejich počet do pocet.",
        "starter_code": "cisla = [1, 2, 2, 3, 3, 3]\nunikatni = set()\npocet = 0\n",
        "hint": "cisla = [1, 2, 2, 3, 3, 3]\nunikatni = set(cisla)\npocet = len(unikatni)",
        "check": 'assert unikatni == {1, 2, 3}, f"Čekal jsem {{1,2,3}}, mám {unikatni}"\nassert pocet == 3, f"Čekal jsem pocet 3, mám {pocet}"',
    },
    {
        "id": 27, "set": 5,
        "title": "Výchozí hodnota parametru",
        "tip": "Parametr funkce může mít výchozí hodnotu, která se použije, když ho při volání nezadáš.",
        "story": "Autopilot zdraví výchozím pozdravem, dokud mu nikdo neřekne jiný.",
        "victory": "Autopilot umí pozdravit i bez zadání, a přesto jde pozdrav změnit.",
        "goal": "Napiš funkci pozdrav(jmeno, pozdrav_slovo='Ahoj'), která vrátí f'{pozdrav_slovo}, {jmeno}!'.",
        "starter_code": "def pozdrav(jmeno, pozdrav_slovo=\"Ahoj\"):\n    pass\n",
        "hint": 'def pozdrav(jmeno, pozdrav_slovo="Ahoj"):\n    return f"{pozdrav_slovo}, {jmeno}!"',
        "check": 'assert pozdrav("Ema") == "Ahoj, Ema!", "Bez druhého argumentu má použít výchozí \'Ahoj\'"\nassert pozdrav("Ema", "Cau") == "Cau, Ema!", "Se zadaným druhým argumentem ho má použít místo výchozího"',
    },
    {
        "id": 28, "set": 5,
        "title": "Ošetři chybu (try/except)",
        "tip": "Někdy se program pokusí o něco, co selže (třeba dělení nulou) - try/except to odchytí, ať program nespadne.",
        "story": "Při výpočtu dráhy se někdo pokusil dělit nulou. Stanice kvůli tomu nesmí spadnout.",
        "victory": "Chyba je odchycená a stanice jede dál.",
        "goal": "Napiš try/except kolem vysledek = 10 / 0, který při chybě ZeroDivisionError vypíše 'Nelze delit nulou'.",
        "starter_code": "\n",
        "hint": 'try:\n    vysledek = 10 / 0\nexcept ZeroDivisionError:\n    print("Nelze delit nulou")',
        "check": 'assert "Nelze delit nulou" in _stdout_capture, "Měl jsi odchytit ZeroDivisionError a vypsat \'Nelze delit nulou\'"',
    },
    {
        "id": 29, "set": 5,
        "title": "Náhodné číslo",
        "tip": "Modul random umí generovat náhodná čísla - třeba pro hru s kostkou.",
        "story": "Meteorický roj přijde v náhodnou chvíli. Potřebuju umět losovat, třeba hodem kostkou.",
        "victory": "Kostka padla. Náhodu už umím.",
        "goal": "Naimportuj random, pak pomocí random.randint(1, 6) ulož do hod výsledek hodu kostkou (číslo 1 až 6).",
        "starter_code": "import random\nhod = 0\n",
        "hint": "import random\nhod = random.randint(1, 6)",
        "check": 'assert isinstance(hod, int) and 1 <= hod <= 6, f"hod musí být celé číslo 1 až 6, mám {hod}"',
    },
    {
        "id": 30, "set": 5,
        "title": "Závěrečná mise: hra s kostkou",
        "tip": "Spoj náhodná čísla, podmínky i funkce do jedné malé hry.",
        "story": "Zkušební let: spojíme náhodu, rozhodování a funkce do jedné malé hry s kostkou.",
        "victory": "Hra s kostkou běží. Zkušební dráha je splněná.",
        "goal": "Napiš funkci hod_kostkou(), která vrátí náhodné číslo 1 až 6 (pomocí random.randint). Pak napiš funkci vyhodnot(hod), která vrátí 'vyhra' pokud je hod == 6, jinak 'zkus znovu'. Zavolej vyhodnot(6) a výsledek vypiš.",
        "starter_code": "import random\n\ndef hod_kostkou():\n    pass\n\ndef vyhodnot(hod):\n    pass\n\n",
        "hint": 'import random\n\ndef hod_kostkou():\n    return random.randint(1, 6)\n\ndef vyhodnot(hod):\n    if hod == 6:\n        return "vyhra"\n    else:\n        return "zkus znovu"\n\nprint(vyhodnot(6))',
        "check": 'assert vyhodnot(6) == "vyhra", "vyhodnot(6) musí vrátit \'vyhra\'"\nassert vyhodnot(3) == "zkus znovu", "vyhodnot(3) musí vrátit \'zkus znovu\'"\nassert "vyhra" in _stdout_capture, "Zapomněl jsi vypsat výsledek vyhodnot(6) pomocí print()"\n_test_hod = hod_kostkou()\nassert isinstance(_test_hod, int) and 1 <= _test_hod <= 6, "hod_kostkou() musí vracet číslo 1 až 6"',
    },

    {
        "id": 31, "set": 6,
        "title": "Jedna volba, tři cesty",
        "tip": "Přesně jako u Iskry - jedna volba může vést na tři různá místa v příběhu.",
        "story": "Holodeck se rozjel, ale zná jen jednu scénu. Naučme ho rozlišit tři cesty.",
        "victory": "Holodeck už umí vybrat scénu podle volby.",
        "goal": "Napiš funkci scena(volba): pro volba==1 vrať 'tovarna', pro volba==2 vrať 'svedek', pro cokoliv jiného vrať 'kabely'. Zavolej scena(2) a výsledek ulož do vysledek.",
        "starter_code": "def scena(volba):\n    pass\n\nvysledek = \"\"\n",
        "hint": 'def scena(volba):\n    if volba == 1:\n        return "tovarna"\n    elif volba == 2:\n        return "svedek"\n    else:\n        return "kabely"\n\nvysledek = scena(2)',
        "check": 'assert scena(1) == "tovarna", "scena(1) musí vrátit \'tovarna\'"\nassert scena(2) == "svedek", "scena(2) musí vrátit \'svedek\'"\nassert scena(3) == "kabely", "scena(3) musí vrátit \'kabely\'"\nassert scena(99) == "kabely", "cokoliv jiného musí spadnout do else větve (kabely)"\nassert vysledek == "svedek", f"vysledek musí být \'svedek\', mám \'{vysledek}\'"',
    },
    {
        "id": 32, "set": 6,
        "title": "Dvě rozhodnutí za sebou",
        "tip": "Skutečné příběhy mívají víc než jedno rozhodnutí za sebou - záleží na kombinaci obou voleb.",
        "story": "Dobrý příběh se větví podle několika voleb za sebou. Zkombinuj dvě rozhodnutí.",
        "victory": "Dvě volby, jedna správná cesta.",
        "goal": "Napiš funkci pribeh(volba1, volba2). Když volba1==1 a volba2==1, vrať 'potichu'. Když volba1==1 a volba2==2, vrať 'primo'. Jinak vrať 'jinam'.",
        "starter_code": "def pribeh(volba1, volba2):\n    pass\n",
        "hint": 'def pribeh(volba1, volba2):\n    if volba1 == 1 and volba2 == 1:\n        return "potichu"\n    elif volba1 == 1 and volba2 == 2:\n        return "primo"\n    else:\n        return "jinam"',
        "check": 'assert pribeh(1, 1) == "potichu"\nassert pribeh(1, 2) == "primo"\nassert pribeh(2, 1) == "jinam"\nassert pribeh(2, 2) == "jinam"',
    },
    {
        "id": 33, "set": 6,
        "title": "Konec podle skóre",
        "tip": "Konec příběhu často závisí na tom, kolik dobrých rozhodnutí jsi cestou udělal.",
        "story": "Podle počtu dobrých rozhodnutí se hráči zobrazí jiný konec.",
        "victory": "Konec se teď volí podle skóre.",
        "goal": "Napiš funkci konec(body): pokud body >= 3 vrať 'vitezstvi', pokud body >= 1 vrať 'castecny_uspech', jinak vrať 'prohra'.",
        "starter_code": "def konec(body):\n    pass\n",
        "hint": 'def konec(body):\n    if body >= 3:\n        return "vitezstvi"\n    elif body >= 1:\n        return "castecny_uspech"\n    else:\n        return "prohra"',
        "check": 'assert konec(0) == "prohra"\nassert konec(1) == "castecny_uspech"\nassert konec(2) == "castecny_uspech"\nassert konec(3) == "vitezstvi"\nassert konec(10) == "vitezstvi"',
    },
    {
        "id": 34, "set": 6,
        "title": "Sečti rozhodnutí do skóre",
        "tip": "Volby v příběhu se dají počítat - a spojit to se smyčkou, kterou už znáš.",
        "story": "Skóre se musí počítat samo. Projdi seznam voleb a započítej ty dobré.",
        "victory": "Skóre se počítá samo.",
        "goal": "Máš volby = [1, 2, 1, 1, 2] (1 = dobré rozhodnutí = +1 bod, cokoliv jiné = 0 bodů). Pomocí for a if spočítej součet do proměnné skore.",
        "starter_code": "volby = [1, 2, 1, 1, 2]\nskore = 0\n\n",
        "hint": "volby = [1, 2, 1, 1, 2]\nskore = 0\nfor v in volby:\n    if v == 1:\n        skore += 1",
        "check": 'assert skore == 3, f"Čekal jsem skore 3, mám {skore}"',
    },
    {
        "id": 35, "set": 6,
        "title": "Závěrečná mise: napiš vlastní mini-příběh",
        "tip": "Teď jsi na řadě ty. Napiš krátkou vlastní větev příběhu - aspoň dva různé konce podle volby.",
        "story": "Teď jsi na řadě ty. Napiš vlastní větev příběhu: na tomhle principu stojí hry v herním sále.",
        "victory": "Tvůj příběh se větví a holodeck je v provozu.",
        "goal": "Napiš funkci muj_pribeh(volba), která pro aspoň 2 různé hodnoty volba vrátí aspoň 2 RŮZNÉ texty (tvoje vlastní konce příběhu). Použij if/elif/else - na obsahu textu nezáleží, jen ať se opravdu liší.",
        "starter_code": "def muj_pribeh(volba):\n    pass\n",
        "hint": 'def muj_pribeh(volba):\n    if volba == 1:\n        return "Vydal ses doleva a nasel poklad!"\n    elif volba == 2:\n        return "Vydal ses doprava a potkal draka."\n    else:\n        return "Zustal jsi stat a nic se nestalo."',
        "check": 'vysledky = [muj_pribeh(1), muj_pribeh(2), muj_pribeh(3)]\nassert all(isinstance(v, str) and len(v) > 0 for v in vysledky), "Funkce musí pro každou volbu vrátit neprázdný text"\nassert len(set(vysledky)) >= 2, "Aspoň dvě různé volby musí vést k různému textu (jinak to není větvení)"',
    },
]


# ---------------------------------------------------------------- příběh
# Pyt je palubní počítač stanice TUX-1 (stejné stanice jako v Pískovišti). Po zkratu přišel o programy
# a kadet mu je v Pythonu píše znovu. Každá sada úkolů je jedna kapitola opravy stanice.
# U úkolu: "story" = děj (hlas Pyta), "tip" = výklad učiva, "victory" = reakce po splnění.
# Zadání ("goal") s příběhem nesouvisí a vždy říká, co přesně udělat.
CHAPTERS = [
    {
        "set": 1,
        "title": "Probuzení",
        "intro": "Zkrat vypnul skoro všechno. Začneme tím nejmenším: ať umím mluvit, pamatovat si, počítat a rozhodovat se.",
        "outro": "Hlavní systémy běží. Umím mluvit, pamatovat si, počítat, rozhodovat se i opakovat. Díky, kadete!"
    },
    {
        "set": 2,
        "title": "Sklad a evidence",
        "intro": "Sklad stanice je plný, ale přišel jsem o evidenci. Seznamy a slovníky mi pomůžou udržet pořádek.",
        "outro": "Evidence je zpátky. Vím, co kde leží a kdo je kdo."
    },
    {
        "set": 3,
        "title": "Dílna",
        "intro": "Psát pořád dokola totéž je zbytečné. V dílně si vyrobíme vlastní nástroje, kterým se říká funkce.",
        "outro": "Dílna běží a nástroje se dají používat znovu a znovu."
    },
    {
        "set": 4,
        "title": "Komunikační centrum",
        "intro": "Ze Země chodí zprávy, měření a povolení. Abych jim rozuměl, musím umět pracovat s texty, čísly i podmínkami.",
        "outro": "Spojení se Zemí je obnovené a poslední zprávy konečně dávají smysl."
    },
    {
        "set": 5,
        "title": "Zkušební dráha",
        "intro": "Před startem musí navigace zvládat souřadnice, chyby i náhodu. Meteorický roj nikdo předem nenaplánuje.",
        "outro": "Zkušební dráha je splněná. Navigace zvládne i chybu ve výpočtu."
    },
    {
        "set": 6,
        "title": "Holodeck",
        "intro": "Poslední sekce stanice je holodeck, kde si posádka hraje příběhy. Rozhodovat se už umíš, teď to využijeme k vyprávění.",
        "outro": "Holodeck je opravený. Teď si v něm můžeš vymýšlet vlastní příběhy."
    }
]

PROLOGUE = "Ahoj, kadete! Jsem Pyt, palubní počítač stanice TUX-1. Po zkratu jsem přišel o všechny programy. Tux opravuje stanici zvenku, z terminálu, a já potřebuju tebe, abys mi programy znovu napsal v Pythonu."

EPILOGUE = "Všechny systémy stanice TUX-1 běží a já mám zpátky hlas i paměť. Z tebe je Pythonista, kadete. Díky!"


def all_tasks():
    return PYTHON_TASKS


def get_task(task_id: int):
    for t in PYTHON_TASKS:
        if t["id"] == task_id:
            return t
    return None
